version: "3"

services:
  db:
    image: postgres
    restart: always
    networks:
      - pg
    volumes:
      - pg:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/db-files/

networks:
  pg:
    driver: bridge

volumes:
  pg:
